### ISSUE TITLE
System state sensor shown as integer

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#99] opened 2021-12-07 12:22 UTC
System state is shown as integer i graphs.

Is there any way of translating these into actual state, Running, Stopped, Fault mode etc?

Or is the documentation lacking?

**Comment by argoyle** [comment] 2021-12-07 12:29
Documentation is lacking as you say. If we know what each bit means we could translate it as we do with a couple of other sensors.

**Comment by bj00rn** [comment] 2021-12-07 16:08
> Documentation is lacking as you say. If we know what each bit means we could translate it as we do with a couple of other sensors.

I can do a little research, `Running Mode`, `Measuring`, and `Stopped` should be easy to pin down.

Fault mode would is a little bit tricker

**Comment by danielolsson100** [comment] 2021-12-07 17:54
I can confirm that the doc is lacking this information and it is by design.
The codes is different status of the EH and is used by the developers at Ferroamp internal only.
I got some undocumented status codes and the code should be not be read as an integer, it should be read in HEX
example:
4097 - is 1001 in HEX and means that you are running  PV in active power automatic mode
4101 - is 1005 in HEX and means that PV and ACE in active power mode

These different setups is defined in the system configuration area in the portal and generates different HEX codes.
Perhaps change the datatype to HEX if it makes sense @argoyle and create a mapping of different codes to text as we did for the SSO status codes **if there is a real need for it.**

**Comment by bj00rn** [comment] 2021-12-07 18:15
> I can confirm that the doc is lacking this information and it is by design. The codes is different status of the EH and is used by the developers at Ferroamp internal only. I got some undocumented status codes and the code should be not be read as an integer, it should be read in HEX example: 4097 - is 1001 in HEX and means that you are running PV in active power automatic mode 4101 - is 1005 in HEX and means that PV and ACE in active power mode
> 
> These different setups is defined in the system configuration area in the portal and generates different HEX codes. Perhaps change the datatype to HEX if it makes sense @argoyle and create a mapping of different codes to text as we did for the SSO status codes **if there is a real need for it.**

No apparent need I would say, just for completeness sake 🚀 

In addition to the modes you mentioned are (at least) `Measuring mode, `Inactive mode` and `Fault mode`.

**Comment by danielolsson100** [comment] 2021-12-08 05:53
@bj00rn if you do the HEX mapping of the different states and add the output here then I can perhaps we can together do something about it.
My workaround regarding this "issue".
I made an automation that checks all SSO states, ESM state, and EH state to make sure that the system works as expected.
If the values are not what they should be then I generate an alarm and sent it as push notice to my phone.
![image](https://user-images.githubusercontent.com/35651684/145155667-d02e1c55-c3b8-4937-9c79-d680bc30c046.png)

**Comment by bj00rn** [comment] 2021-12-08 08:11
> ping of the different states and add the output here then I can perhaps we can together do something about it.

Nice! Sure, I will look into it!

**Comment by bj00rn** [comment] 2021-12-13 09:45
hmm not as straightforward as i imagined

When stopping and starting the EH (PV & ACE) it goes through:

Stopping
4101  -> Shows "Running" in Portal
2381 -> Shows "Measuring" in Portal
1374 -> Shows "Stopped" in Portal

Starting
4098 -> Shows "Measuring" in Portal
4101  -> Shows "Running" in Portal

**Comment by danielolsson100** [comment] 2022-07-14 05:54
We don't have any official doc from ferroamp and I don't think that we will get any because theses codes har for internal use for ferroamp for now.

Shall we close this issue @bj00rn @argoyle

**Comment by argoyle** [comment] 2022-07-14 14:04
I think we can close it for now and either reopen och just PR if/when we get any official docs.

**Closed** 2022-07-14 14:16 UTC
